### ISSUE TITLE
ripemd160 support deprecated in OpenSSL v3 / Ubuntu 22:04

### ISSUE THREAD

**Issue by Teasel-Ian** [fetchai/cosmpy#144]
**Issue:**
The OpenSSL v3.0 library, which ships with eg Ubuntu 22.04 LTS, does not support ripemd160 by default.  (The legacy provider would need to be explicitly enabled in openssl.cnf by the user)

**Minimal Example:**
Dockerfile:
```docker
FROM ubuntu:22.04
RUN apt-get update
RUN apt-get install -y python3 pip
RUN pip install cosmpy
WORKDIR /app
COPY test.py /app
CMD [ "python3", "./test.py"]
```
test.py:
```python
from cosmpy.aerial.wallet import LocalWallet
from cosmpy.crypto.keypairs import PrivateKey

alice = LocalWallet(PrivateKey("T7w1yHq1QIcQiSqV27YSwk+i1i+Y4JMKhkpawCQIh6s="))
print(f"Alice Address: {alice.address()}")
```

[Fails here](https://github.com/fetchai/cosmpy/blob/6d7b5f49722b67c803145d55aa291fe426c19994/cosmpy/crypto/hashfuncs.py#L52) with...
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/hashlib.py", line 160, in __hash_new
    return _hashlib.new(name, data, **kwargs)
ValueError: [digital envelope routines] unsupported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/./test.py", line 5, in <module>
    print(f"Alice Address: {alice.address()}")
  File "/usr/local/lib/python3.10/dist-packages/cosmpy/aerial/wallet.py", line 50, in address
    return Address(self._private_key)
  File "/usr/local/lib/python3.10/dist-packages/cosmpy/crypto/address.py", line 76, in __init__
    self._address = ripemd160(sha256(value.public_key_bytes))
  File "/usr/local/lib/python3.10/dist-packages/cosmpy/crypto/hashfuncs.py", line 52, in ripemd160
    h: HASH = hashlib.new("ripemd160")
  File "/usr/lib/python3.10/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/usr/lib/python3.10/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type ripemd160
```
...whereas change the Dockerfile to a linux distro still on OpenSSL v1.1, eg ubuntu:20.04 and it gives the expected output...
```
Alice Address: fetch17x574akd6kt8y7tqz5p2cft605ns7t826zpavy
```
**Possible solutions**

Other crypto projects have worked around this by falling back to a pure python ripemd160 when hashlib fails to deliver, (eg [bitcoin-core](https://github.com/bitcoin/bitcoin/pull/23716), [electrum](https://github.com/spesmilo/electrum/blob/0df05dd914c823acae1828cad3b20bdeb13150e9/electrum/crypto.py#L312-L324) )

**Comment by Teasel-Ian** [comment]
One possible replacement: https://pycryptodome.readthedocs.io/en/latest/src/hash/ripemd160.html

**Comment by 5A11** [comment]
This should be in now #192.
