### ISSUE TITLE
Account sequence Mismatch

### ISSUE THREAD

**Issue by dishmop** [fetchai/cosmpy#205]
### Prerequisites

- [X] I am running the [latest CosmPy version](https://docs.fetch.ai/CosmPy/#version).
- [X] I checked the [documentation](http://docs.fetch.ai/CosmPy/) and found no answer to my problem.
- [X] I checked the [existing issues](https://github.com/fetchai/cosmpy/issues) to make sure my problem has not already been reported.
- [X] I have read the [code of conduct](https://github.com/fetchai/cosmpy/blob/master/CODE_OF_CONDUCT.md) before creating this issue.

### Expected Behavior

When I issue a transaction to a contract from cosmpy - i exepct it to execute.  If there is a mismatch of account sequence Ids - can cosmpy just display a warning, get the correct sequence Id and then try again?

### Current Behavior

Sometimes we get this error:
```
Deploying Atomix Mint contract: Traceback (most recent call last):
  File "/Users/diarmidcampbell/Projects/atomix/atomix_contracts/tools/june2022_demo_startup.py", line 21, in <module>
    cc = deployment.deploy(admin_mnemonic, addresses_filename)
  File "/Users/diarmidcampbell/Projects/atomix/atomix_contracts/atomix_contracts/deployment.py", line 13, in deploy
    deploy_all(cc, acc_admin)
  File "/Users/diarmidcampbell/Projects/atomix/atomix_contracts/atomix_contracts/deployment.py", line 113, in deploy_all
    cc.atomix_mint.deploy(
  File "/Users/diarmidcampbell/.local/share/virtualenvs/atomix_contracts-enN6ABIN/lib/python3.9/site-packages/cosmpy/aerial/contract/__init__.py", line 159, in deploy
    return self.instantiate(
  File "/Users/diarmidcampbell/.local/share/virtualenvs/atomix_contracts-enN6ABIN/lib/python3.9/site-packages/cosmpy/aerial/contract/__init__.py", line 126, in instantiate
    submitted_tx = prepare_and_broadcast_basic_transaction(
  File "/Users/diarmidcampbell/.local/share/virtualenvs/atomix_contracts-enN6ABIN/lib/python3.9/site-packages/cosmpy/aerial/client/utils.py", line 53, in prepare_and_broadcast_basic_transaction
    gas_limit, fee = client.estimate_gas_and_fee_for_tx(tx)
  File "/Users/diarmidcampbell/.local/share/virtualenvs/atomix_contracts-enN6ABIN/lib/python3.9/site-packages/cosmpy/aerial/client/__init__.py", line 411, in estimate_gas_and_fee_for_tx
    gas_estimate = self.estimate_gas_for_tx(tx)
  File "/Users/diarmidcampbell/.local/share/virtualenvs/atomix_contracts-enN6ABIN/lib/python3.9/site-packages/cosmpy/aerial/client/__init__.py", line 405, in estimate_gas_for_tx
    return self._gas_strategy.estimate_gas(tx)
  File "/Users/diarmidcampbell/.local/share/virtualenvs/atomix_contracts-enN6ABIN/lib/python3.9/site-packages/cosmpy/aerial/gas.py", line 51, in estimate_gas
    gas_estimate = self._client.simulate_tx(tx)
  File "/Users/diarmidcampbell/.local/share/virtualenvs/atomix_contracts-enN6ABIN/lib/python3.9/site-packages/cosmpy/aerial/client/__init__.py", line 494, in simulate_tx
    resp = self.txs.Simulate(req)
  File "/Users/diarmidcampbell/.local/share/virtualenvs/atomix_contracts-enN6ABIN/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/diarmidcampbell/.local/share/virtualenvs/atomix_contracts-enN6ABIN/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "account sequence mismatch, expected 744, got 743: incorrect account sequence"
	debug_error_string = "{"created":"@1657879900.158507000","description":"Error received from peer ipv4:172.66.40.149:443","file":"src/core/lib/surface/call.cc","file_line":953,"grpc_message":"account sequence mismatch, expected 744, got 743: incorrect account sequence","grpc_status":2}"
```

### To Reproduce

It is somewhat intermittent. It can happen if two people are using the same wallet to perform transactions at the same time. 

However, we have also had it when just one person is using an account - perhaps running different python scripts in different terminals...not sure. I'mpretty sure Ive had it when I have just one script running and no-one else using the account - but I can't be certain. 

### Context

OSX and linux.

**Comment by solarw** [comment]
@dishmop 
it's a common issue when seq number is out of sync.
only one good way: make call sequentially and wait for tx to be settled on the ledger side

**Comment by 5A11** [comment]
@dishmop should we close this issue given the above?

**Comment by dishmop** [comment]
Yes fine to close
