### ISSUE TITLE
Bug report: <short description>

### ISSUE THREAD

**Issue by qwertyNodes** [fetchai/cosmpy#266]
### Prerequisites

- [X] I am running the [latest CosmPy version](https://docs.fetch.ai/CosmPy/#version).
- [X] I checked the [documentation](http://docs.fetch.ai/CosmPy/) and found no answer to my problem.
- [X] I checked the [existing issues](https://github.com/fetchai/cosmpy/issues) to make sure my problem has not already been reported.
- [X] I have read the [code of conduct](https://github.com/fetchai/cosmpy/blob/master/CODE_OF_CONDUCT.md) before creating this issue.

### Expected Behavior

I expected to receive the cosmos hub's wallet balance:

`tests_address = 'cosmos1rtpgucu3pjrelph4flzg6hr5ntt6yw56l0qvx5'

    generated_wallet = LocalWallet.generate(prefix='cosmos')

    cfg = NetworkConfig(
        chain_id="Cosmos-Hub",
        url="grpc+https://grpc-cosmoshub.blockapsis.com:429",
        fee_minimum_gas_price=1,
        fee_denomination="uatom",
        staking_denomination="uatom",
    )
    cl = LedgerClient(cfg)

    res = cl.query_account(address=Address(tests_address))`

### Current Behavior

Getting the error:
---------------------
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Received http2 header with status: 502"
	debug_error_string = "{"created":"@1661773704.783000000","description":"Error received from peer ipv4:52.9.100.62:429","file":"src/core/lib/surface/call.cc","file_line":967,"grpc_message":"Received http2 header with status: 502","grpc_status":14}"
>
python-BaseException

Process finished with exit code 1

### To Reproduce

`tests_address = 'cosmos1rtpgucu3pjrelph4flzg6hr5ntt6yw56l0qvx5'

    generated_wallet = LocalWallet.generate(prefix='cosmos')

    cfg = NetworkConfig(
        chain_id="Cosmos-Hub",
        url="grpc+https://grpc-cosmoshub.blockapsis.com:429",
        fee_minimum_gas_price=1,
        fee_denomination="uatom",
        staking_denomination="uatom",
    )
    cl = LedgerClient(cfg)

    res = cl.query_account(address=Address(tests_address))`

### Context

Trying to receive wallet balance

### Failure Logs

E0829 14:48:24.782000000 18932 src/core/ext/transport/chttp2/transport/hpack_parser.cc:1234] Error parsing metadata: error=invalid value key=content-type value=text/html
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2022.1.2\plugins\python\helpers\pydev\pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2022.1.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Python_Projects/Cosmos_Client/tests/test_client.py", line 20, in <module>
    res = cl.query_account(address=Address(tests_address))
  File "D:\Python_Projects\Cosmos_Client\venv\lib\site-packages\cosmpy\aerial\client\__init__.py", line 200, in query_account
    response = self.auth.Account(request)
  File "D:\Python_Projects\Cosmos_Client\venv\lib\site-packages\grpc\_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "D:\Python_Projects\Cosmos_Client\venv\lib\site-packages\grpc\_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Received http2 header with status: 502"
	debug_error_string = "{"created":"@1661773704.783000000","description":"Error received from peer ipv4:52.9.100.62:429","file":"src/core/lib/surface/call.cc","file_line":967,"grpc_message":"Received http2 header with status: 502","grpc_status":14}"

**Comment by qwertyNodes** [comment]
was not a bug, just not working chain URL
