### ISSUE TITLE
Bug report: Can not install cosmpy

### ISSUE THREAD

**Issue by lehieuhust** [fetchai/cosmpy#341]
### Prerequisites

- [X] I am running the [latest CosmPy version](https://docs.fetch.ai/CosmPy/#version).
- [X] I checked the [documentation](http://docs.fetch.ai/CosmPy/) and found no answer to my problem.
- [X] I checked the [existing issues](https://github.com/fetchai/cosmpy/issues) to make sure my problem has not already been reported.
- [X] I have read the [code of conduct](https://github.com/fetchai/cosmpy/blob/master/CODE_OF_CONDUCT.md) before creating this issue.

### Expected Behavior

Success install cosmpy

### Current Behavior

pip3 install cosmpy

### To Reproduce

Hello, I have installed cosmpy and faced this error. Can anyone explain to me about this error? How to fix it?

### Context

```
python3 --version                                                                                                                                                                                                      
Python 3.11.2
```
`Mac os version 12.5
Chip Apple M1 pro`

### Failure Logs
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/x5/cp6j19k57ll8bvr0nxjwgscw0000gn/T/pip-install-f8vh8fnh/grpcio_46a95b6e150e45928599ee4f2a5cdbe7/setup.py", line 541, in <module>
          setuptools.setup(
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/private/var/folders/x5/cp6j19k57ll8bvr0nxjwgscw0000gn/T/pip-install-f8vh8fnh/grpcio_46a95b6e150e45928599ee4f2a5cdbe7/src/python/grpcio/commands.py", line 283, in build_extensions
          support.diagnose_build_ext_error(self, error, formatted_exception)
        File "/private/var/folders/x5/cp6j19k57ll8bvr0nxjwgscw0000gn/T/pip-install-f8vh8fnh/grpcio_46a95b6e150e45928599ee4f2a5cdbe7/src/python/grpcio/support.py", line 117, in diagnose_build_ext_error
          diagnostic(build_ext, error)
        File "/private/var/folders/x5/cp6j19k57ll8bvr0nxjwgscw0000gn/T/pip-install-f8vh8fnh/grpcio_46a95b6e150e45928599ee4f2a5cdbe7/src/python/grpcio/support.py", line 96, in diagnose_attribute_error
          raise commands.CommandError(
      commands.CommandError: We expect a missing `_needs_stub` attribute from older versions of setuptools. Consider upgrading setuptools.
      [end of output]

**Comment by jrriehl** [comment]
Due to some downstream dependencies, CosmPy does not yet support Python 3.11. We are hoping to add this support soon: https://github.com/fetchai/cosmpy/issues/326.

**Comment by jrriehl** [comment]
Support for Python 3.11 added here: https://github.com/fetchai/cosmpy/pull/350.
