### ISSUE TITLE
 No module named 'gogoproto' when using pyinstaller

### ISSUE THREAD

**Issue by henzycuong1** [fetchai/cosmpy#399]
### Prerequisites

- [X] I checked the [documentation](https://fetch.ai/docs) and found no answer to my problem
- [X] I checked the [existing issues](https://github.com/fetchai/cosmpy/issues) and made sure there are no similar bug reports

### Category

Other

### Observed Behavior

I used pyinstaller to generate the exe file but when I run the file it gives me an error "No module named 'gogoproto' " while I can still run it on my source code.
```
Traceback (most recent call last):
  File "swap.py", line 9, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "cosmpy\aerial\client\__init__.py", line 34, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "cosmpy\aerial\client\bank.py", line 23, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "cosmpy\protos\cosmos\bank\v1beta1\tx_pb2.py", line 15, in <module>
ModuleNotFoundError: No module named 'gogoproto'
[15000] Failed to execute script 'swap' due to unhandled exception!
```

### Version

0.5.0

**Comment by kshipra-fetch** [comment]
Hi @henzycuong1 

Thank you for reporting this issue.
@pbukva Could you please take a look at this issue?
